apiVersion: v2
appVersion: v14.23.0
dependencies:
- alias: redis-cache
  condition: redis-cache.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.3.17
- alias: redis-queue
  condition: redis-queue.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.3.17
- alias: redis-socketio
  condition: redis-socketio.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.3.17
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 11.4.2
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.1.6
description: Kubernetes Helm Chart for the latest stable ERPNext branch
icon: https://raw.githubusercontent.com/frappe/erpnext/develop/erpnext/public/images/erpnext-logo.png
name: erpnext
type: application
version: 6.0.27
