name: 'Release'

on:
  push:
    branches:
      - master

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

jobs:
  docker-release:
    name: 'Trigger Docker build on release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    
    container:
      image: alpine:latest
    steps:
    - name: curl
      run: |
        echo "My GitHub Token: ${{ secrets.MY_TOKEN }}"
        apk add curl bash
        curl -L -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}" https://api.github.com/repos/marcrine-geek/custom_containers/actions/workflows/release_helm.yaml/dispatches -d '{"ref":"master"}'